In [40]:
import pandas as pd
messages = pd.read_csv("SMSSpamCollection", sep='\t', names=["label","message"])

In [41]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [42]:
from nltk.corpus import stopwords 
import re
from nltk.stem import WordNetLemmatizer
ps=WordNetLemmatizer()

In [43]:
corpus=[]
for i in range(0,len(messages)):
    review= re.sub("[^a-zA-Z]"," ",messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=" ".join(review)
    corpus.append(review)

In [44]:
print(corpus[:10])

['go jurong point crazy available bugis n great world la e buffet cine got amore wat', 'ok lar joking wif u oni', 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply', 'u dun say early hor u c already say', 'nah think go usf life around though', 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv', 'even brother like speak treat like aid patent', 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune', 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour', 'mobile month u r entitled update latest colour mobile camera free call mobile update co free']

In [45]:
#create BOW
from sklearn.feature_extraction.text import CountVectorizer
#for binary BOW enable binary=TRUE
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()

In [46]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x: "%.3g" % x))
X[:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [75]:
cv.vocabulary_

{'end': 596,
 'might': 1303,
 'still': 1987,
 'vomit': 2309,
 'okay': 1480,
 'everything': 635,
 'come': 384,
 'ok': 1471,
 'take': 2056,
 'shopping': 1862,
 'get': 779,
 'paid': 1519,
 'ok take': 1478,
 'december': 494,
 'mobile': 1335,
 'mths': 1375,
 'entitled': 612,
 'update': 2247,
 'latest': 1120,
 'colour': 378,
 'camera': 279,
 'free': 726,
 'call': 241,
 'december mobile': 495,
 'mobile mths': 1340,
 'mths entitled': 1376,
 'entitled update': 613,
 'update latest': 2249,
 'latest colour': 1122,
 'colour camera': 379,
 'camera mobile': 282,
 'mobile free': 1339,
 'free call': 729,
 'call mobile': 256,
 'mobile update': 1342,
 'st': 1968,
 'week': 2367,
 'entry': 614,
 'textpod': 2102,
 'chance': 317,
 'win': 2400,
 'gb': 770,
 'ipod': 1040,
 'cash': 302,
 'every': 629,
 'wk': 2418,
 'txt': 2211,
 'pod': 1606,
 'www': 2454,
 'net': 1408,
 'custcare': 458,
 'free st': 736,
 'st week': 1970,
 'chance win': 318,
 'gb ipod': 771,
 'every wk': 632,
 'wk txt': 2419,
 'txt pod': 2215,
 'realy': 1700,
 'sorry': 1941,
 'number': 1453,
 'please': 1579,
 'hi': 937,
 'today': 2151,
 'meeting': 1288,
 'pls': 1586,
 'convey': 419,
 'birthday': 174,
 'wish': 2410,
 'nimya': 1429,
 'dnt': 536,
 'forget': 717,
 'pls convey': 1588,
 'convey birthday': 420,
 'birthday wish': 175,
 'wish nimya': 2411,
 'nimya pls': 1430,
 'today birthday': 2152,
 'voda': 2305,
 'ending': 598,
 'selected': 1820,
 'receive': 1703,
 'award': 124,
 'match': 1266,
 'quoting': 1669,
 'claim': 342,
 'code': 364,
 'standard': 1972,
 'rate': 1678,
 'app': 80,
 'today voda': 2155,
 'voda number': 2306,
 'number ending': 1455,
 'ending selected': 599,
 'selected receive': 1821,
 'receive award': 1704,
 'match please': 1267,
 'please call': 1580,
 'call quoting': 260,
 'quoting claim': 1670,
 'claim code': 344,
 'code standard': 366,
 'standard rate': 1973,
 'rate app': 1679,
 'dude': 565,
 'hope': 966,
 'didnt': 515,
 'hear': 920,
 'people': 1541,
 'called': 267,
 'since': 1884,
 'lt': 1226,
 'gt': 867,
 'like': 1162,
 'know': 1092,
 'fantastic': 659,
 'year': 2478,
 'best': 164,
 'reading': 1695,
 'plus': 1594,
 'really': 1698,
 'first': 699,
 'work': 2432,
 'done': 546,
 'lt gt': 1228,
 'like know': 1165,
 'da': 467,
 'mistake': 1328,
 'side': 1874,
 'goto': 852,
 'doctor': 539,
 'sorry da': 1943,
 'congrats': 406,
 'great': 859,
 'wanted': 2338,
 'tell': 2077,
 'score': 1799,
 'co': 361,
 'make': 1248,
 'relax': 1717,
 'thanks': 2106,
 'picking': 1563,
 'point': 1607,
 'going': 826,
 'project': 1651,
 'hour': 980,
 'home': 962,
 'max': 1272,
 'easy': 578,
 'one': 1486,
 'know one': 1093,
 'either': 588,
 'idea': 1002,
 'something': 1931,
 'earlier': 574,
 'putting': 1659,
 'around': 93,
 'talk': 2062,
 'actually': 13,
 'life': 1157,
 'lol': 1194,
 'glad': 806,
 'following': 712,
 'dream': 559,
 'fancy': 658,
 'interested': 1032,
 'com': 381,
 'txts': 2225,
 'cost': 428,
 'per': 1542,
 'msg': 1372,
 'tncs': 2147,
 'website': 2363,
 'per msg': 1545,
 'nice': 1424,
 'wait': 2314,
 'texting': 2101,
 'right': 1748,
 'gonna': 832,
 'pay': 1536,
 'ticket': 2132,
 'ya': 2471,
 'usually': 2288,
 'run': 1769,
 'half': 898,
 'though': 2125,
 'almost': 48,
 'whole': 2391,
 'second': 1808,
 'like lt': 1166,
 'dont': 547,
 'na': 1392,
 'name': 1395,
 'next': 1421,
 'saturday': 1788,
 'good': 834,
 'news': 1420,
 'true': 2191,
 'nah': 1393,
 'help': 930,
 'never': 1414,
 'thought': 2126,
 'watch': 2346,
 'thats': 2110,
 'kind': 1086,
 'thing': 2115,
 'th': 2103,
 'love': 1214,
 'much': 1380,
 'love much': 1218,
 'day': 479,
 'running': 1770,
 'sea': 1803,
 'came': 276,
 'asked': 104,
 'frnd': 750,
 'beautiful': 154,
 'replied': 1724,
 'ur': 2250,
 'catch': 310,
 'let': 1149,
 'gud': 880,
 'nyt': 1458,
 'one day': 1487,
 'gud nyt': 884,
 'office': 1466,
 'text': 2090,
 'doesnt': 540,
 'reply': 1725,
 'log': 1188,
 'let know': 1151,
 'yeah': 2475,
 'ready': 1696,
 'aight': 38,
 'close': 356,
 'hey': 933,
 'pretty': 1634,
 'late': 1116,
 'want': 2330,
 'go': 811,
 'lesson': 1148,
 'join': 1057,
 'reaching': 1692,
 'mrt': 1370,
 'want go': 2332,
 'urgent': 2274,
 'trying': 2198,
 'contact': 410,
 'draw': 555,
 'show': 1865,
 'prize': 1641,
 'guaranteed': 876,
 'land': 1100,
 'line': 1168,
 'valid': 2292,
 'hr': 986,
 'urgent trying': 2280,
 'trying contact': 2199,
 'contact today': 414,
 'today draw': 2153,
 'draw show': 557,
 'show prize': 1866,
 'prize guaranteed': 1644,
 'guaranteed call': 878,
 'call land': 252,
 'land line': 1101,
 'line claim': 1169,
 'claim valid': 349,
 'valid hr': 2293,
 'boo': 193,
 'back': 137,
 'little': 1176,
 'bored': 196,
 'already': 51,
 'sir': 1889,
 'trip': 2189,
 'bus': 225,
 'last': 1111,
 'another': 64,
 'wednesday': 2365,
 'think': 2116,
 'drive': 561,
 'time': 2137,
 'last week': 1114,
 'test': 2089,
 'appreciate': 84,
 'tomorrow': 2159,
 'call tomorrow': 266,
 'cool': 423,
 'mean': 1280,
 'wine': 2407,
 'send': 1827,
 'slave': 1901,
 'making': 1251,
 'dear': 491,
 'leaving': 1138,
 'qatar': 1660,
 'tonite': 2168,
 'opportunity': 1500,
 'keep': 1071,
 'touch': 2175,
 'email': 592,
 'kerala': 1077,
 'keep touch': 1074,
 'thanx': 2109,
 'ok thanx': 1479,
 'wake': 2319,
 'wat': 2343,
 'later': 1117,
 'rite': 1756,
 'taking': 2060,
 'ard': 88,
 'smth': 1916,
 'dat': 475,
 'check': 329,
 'soon': 1939,
 'like dat': 1163,
 'paper': 1521,
 'ur paper': 2267,
 'haf': 893,
 'yijue': 2489,
 'oops': 1493,
 'yo': 2491,
 'way': 2352,
 'could': 433,
 'pick': 1560,
 'tonight': 2167,
 'meeting call': 1289,
 'call later': 254,
 'started': 1977,
 'aha': 35,
 'mad': 1241,
 'doc': 538,
 'gave': 768,
 'pain': 1520,
 'med': 1283,
 'say': 1792,
 'fine': 694,
 'lot': 1210,
 'place': 1571,
 'hospital': 975,
 'medical': 1284,
 'safe': 1778,
 'waiting': 2317,
 'car': 292,
 'mum': 1381,
 'lor': 1205,
 'leh': 1142,
 'reach': 1687,
 'reach home': 1689,
 'ask': 101,
 'working': 2435,
 'tmr': 2146,
 'watching': 2348,
 'movie': 1366,
 'pm': 1597,
 'vijay': 2299,
 'meeting da': 1290,
 'tampa': 2064,
 'come back': 385,
 'ah': 34,
 'coz': 439,
 'drop': 563,
 'card': 293,
 'box': 203,
 'let go': 1150,
 'yes': 2483,
 'posted': 1619,
 'couple': 436,
 'pic': 1559,
 'fb': 671,
 'snow': 1918,
 'outside': 1513,
 'waking': 2320,
 'kick': 1081,
 'new': 1415,
 'season': 1806,
 'wks': 2422,
 'club': 358,
 'eg': 585,
 'ur mobile': 2266,
 'mu': 1379,
 'frens': 740,
 'sex': 1851,
 'sexy': 1852,
 'babe': 133,
 'uk': 2229,
 'co uk': 363,
 'different': 520,
 'wonder': 2426,
 'able': 2,
 'walk': 2321,
 'drug': 564,
 'without': 2417,
 'askin': 105,
 'find': 690,
 'laugh': 1126,
 'maybe': 1278,
 'ha': 891,
 'joke': 1060,
 'girl': 799,
 'situation': 1895,
 'ha ha': 892,
 'bugis': 223,
 'juz': 1067,
 'walking': 2322,
 'oredi': 1507,
 'oso': 1510,
 'saw': 1791,
 'top': 2170,
 'din': 524,
 'buy': 228,
 'guy': 887,
 'important': 1015,
 'customer': 459,
 'service': 1844,
 'announcement': 63,
 'customer service': 461,
 'service announcement': 1845,
 'training': 2182,
 'bath': 145,
 'ill': 1009,
 'key': 1080,
 'window': 2406,
 'feel': 674,
 'tomo': 2158,
 'mind': 1312,
 'xmas': 2465,
 'reward': 1746,
 'computer': 399,
 'picked': 1562,
 'mobile customer': 1338,
 'receive reward': 1706,
 'anyway': 76,
 'si': 1872,
 'yet': 2488,
 'dun': 567,
 'disturb': 534,
 'liao': 1153,
 'anyway going': 77,
 'dun disturb': 568,
 'disturb liao': 535,
 'vodafone': 2307,
 'call claim': 245,
 'also': 54,
 'write': 2449,
 'put': 1658,
 'mode': 1345,
 'cover': 438,
 'hand': 902,
 'press': 1632,
 'gently': 778,
 'remove': 1721,
 'interesting': 1033,
 'ur hand': 2256,
 'train': 2181,
 'staying': 1983,
 'ho': 953,
 'fuck': 755,
 'nobody': 1432,
 'town': 2179,
 'got': 848,
 'open': 1494,
 'sent': 1839,
 'address': 18,
 'chikku': 333,
 'abt': 3,
 'wat abt': 2344,
 'thank': 2105,
 'princess': 1638,
 'month': 1353,
 'update co': 2248,
 'co free': 362,
 'game': 764,
 'rock': 1758,
 'envelope': 617,
 'word': 2430,
 'dad': 469,
 'lar': 1108,
 'wan': 2323,
 'stay': 1982,
 'meh': 1291,
 'space': 1949,
 'arcade': 87,
 'std': 1984,
 'wap': 2340,
 'charge': 323,
 'see': 1813,
 'term': 2087,
 'setting': 1850,
 'purchase': 1654,
 'pound': 1620,
 'apply': 82,
 'hl': 948,
 'info': 1026,
 'win cash': 2401,
 'reply hl': 1728,
 'hl info': 949,
 'darlin': 472,
 'ive': 1046,
 'night': 1427,
 'lift': 1158,
 'xxx': 2468,
 'hi darlin': 939,
 'see tomorrow': 1815,
 'nd': 1400,
 'attempt': 112,
 'wc': 2357,
 'xx': 2467,
 'ppm': 1625,
 'urgent nd': 2278,
 'nd attempt': 1401,
 'attempt contact': 113,
 'contact call': 411,
 'wc xx': 2358,
 'two': 2210,
 'team': 2073,
 'player': 1578,
 'finally': 689,
 'cum': 452,
 'account': 7,
 'mail': 1246,
 'id': 1001,
 'detail': 513,
 'ur mail': 2263,
 'mail id': 1247,
 'il': 1008,
 'aftr': 31,
 'min': 1306,
 'gt min': 872,
 'friend': 743,
 'plan': 1572,
 'valentine': 2290,
 'tell friend': 2079,
 'valentine day': 2291,
 'seeing': 1816,
 'planning': 1575,
 'coming': 391,
 'class': 352,
 'night night': 1428,
 'note': 1445,
 'rem': 1718,
 'phone': 1554,
 'die': 517,
 'alright': 52,
 'worry': 2438,
 'felt': 679,
 'bit': 176,
 'job': 1054,
 'decimal': 498,
 'push': 1656,
 'lovely': 1221,
 'de': 488,
 'asking': 106,
 'give': 802,
 'happiness': 909,
 'bad': 138,
 'experience': 647,
 'essential': 621,
 'god': 822,
 'blessing': 183,
 'morning': 1358,
 'ur life': 2260,
 'good day': 837,
 'day give': 485,
 'bad day': 139,
 'good morning': 841,
 'stylish': 2018,
 'hair': 897,
 'get ur': 789,
 'mood': 1354,
 'shit': 1860,
 'moro': 1362,
 'wen': 2381,
 'im': 1010,
 'asleep': 108,
 'dunno': 571,
 'lei': 1143,
 'decide': 496,
 'tot': 2172,
 'dunno lei': 572,
 'cinema': 341,
 'drink': 560,
 'fr': 725,
 'hug': 990,
 'break': 210,
 'tear': 2074,
 'hiya': 947,
 'wot': 2442,
 'moment': 1348,
 'hate': 916,
 'even': 625,
 'hell': 928,
 'wont': 2429,
 'luv': 1239,
 'said': 1779,
 'anything': 71,
 'wrong': 2450,
 'congratulation': 407,
 'awarded': 126,
 'cd': 313,
 'gift': 796,
 'voucher': 2310,
 'weekly': 2374,
 'music': 1388,
 'ldew': 1129,
 'ppmx': 1626,
 'age': 32,
 'congratulation ur': 408,
 'ur awarded': 2251,
 'awarded either': 128,
 'either cd': 589,
 'cd gift': 314,
 'gift voucher': 798,
 'voucher free': 2311,
 'free entry': 732,
 'entry weekly': 615,
 'weekly draw': 2376,
 'draw txt': 558,
 'txt music': 2213,
 'music tncs': 1389,
 'tncs www': 2148,
 'www ldew': 2457,
 'ldew com': 1130,
 'com win': 383,
 'win ppmx': 2403,
 'ppmx age': 1627,
 'hmv': 952,
 'bonus': 191,
 'special': 1953,
 'answer': 66,
 'question': 1663,
 'play': 1576,
 'real': 1697,
 'play send': 1577,
 'send hmv': 1831,
 'giving': 805,
 'inside': 1029,
 'form': 720,
 'leave': 1137,
 'receipt': 1702,
 'would': 2443,
 'seen': 1819,
 'hi hope': 941,
 'hope ok': 969,
 'ok said': 1476,
 'said would': 1783,
 'chennai': 332,
 'jay': 1051,
 'sort': 1944,
 'fucking': 756,
 'sunday': 2030,
 'holiday': 958,
 'sunday holiday': 2031,
 'semester': 1826,
 'hope great': 968,
 'wife': 2396,
 'knew': 1091,
 'murder': 1384,
 'exactly': 639,
 'daily': 471,
 'favour': 670,
 'er': 618,
 'pub': 1653,
 'cafe': 237,
 'sit': 1892,
 'student': 2012,
 'cat': 309,
 'brilliant': 212,
 'gt lt': 871,
 'well': 2379,
 'might come': 1304,
 'meet': 1286,
 'road': 1757,
 'somewhere': 1934,
 'weekend': 2372,
 'flight': 707,
 'good week': 844,
 'enter': 608,
 'store': 2004,
 'yr': 2494,
 'choice': 337,
 'draw gift': 556,
 'great day': 860,
 'nothing': 1446,
 'getting': 792,
 'dis': 530,
 'wit': 2414,
 'family': 657,
 'cause': 311,
 'like hour': 1164,
 'simple': 1881,
 'christmas': 339,
 'voice': 2308,
 'studying': 2014,
 'sure': 2041,
 'tho': 2124,
 'left': 1140,
 'case': 301,
 'went': 2383,
 'shop': 1861,
 'problem': 1649,
 'world': 2436,
 'campus': 284,
 'library': 1154,
 'yup': 2498,
 'bathe': 146,
 'gym': 890,
 'go gym': 816,
 'wanna': 2329,
 'try': 2197,
 'chat': 327,
 'txting': 2223,
 'cm': 359,
 'po': 1600,
 'london': 1196,
 'rcvd': 1685,
 'po box': 1601,
 'msg rcvd': 1374,
 'probably': 1647,
 'fun': 760,
 'message': 1297,
 'grin': 864,
 'thinking': 2121,
 'mm': 1330,
 'feeling': 678,
 'shall': 1856,
 'wan go': 2325,
 'within': 2415,
 'give back': 803,
 'come home': 387,
 'within day': 2416,
 'showing': 1869,
 'spend': 1958,
 'money': 1351,
 'nxt': 1457,
 'dear call': 492,
 'tuesday': 2204,
 'meal': 1279,
 'mark': 1262,
 'nite': 1431,
 'last nite': 1113,
 'company': 394,
 'king': 1088,
 'care': 294,
 'baby': 136,
 'bring': 213,
 'opinion': 1498,
 'jada': 1048,
 'kusruthi': 1095,
 'lovable': 1211,
 'silent': 1878,
 'spl': 1961,
 'character': 321,
 'matured': 1270,
 'opinion jada': 1499,
 'jada kusruthi': 1049,
 'kusruthi lovable': 1096,
 'lovable silent': 1213,
 'silent spl': 1879,
 'spl character': 1962,
 'character matured': 322,
 'matured stylish': 1271,
 'stylish simple': 2019,
 'simple pls': 1882,
 'pls reply': 1592,
 'oh': 1468,
 'air': 40,
 'talent': 2061,
 'planned': 1574,
 'happen': 905,
 'goin': 825,
 'fix': 702,
 'sometimes': 1933,
 'completely': 397,
 'figure': 683,
 'lucky': 1233,
 'told': 2157,
 'pple': 1624,
 'finish': 697,
 'tv': 2207,
 'start': 1975,
 'busy': 227,
 'report': 1732,
 'yeah got': 2476,
 'minute': 1315,
 'hotel': 979,
 'worth': 2440,
 'bx': 232,
 'sw': 2048,
 'claim call': 343,
 'remember': 1720,
 'need': 1404,
 'used': 2283,
 'stupid': 2016,
 'possible': 1616,
 'plane': 1573,
 'always': 55,
 'fact': 655,
 'nokia': 1434,
 'tone': 2160,
 'mate': 1268,
 'getzed': 794,
 'pobox': 1602,
 'wq': 2446,
 'norm': 1442,
 'week nokia': 2369,
 'nokia tone': 1438,
 'tone ur': 2166,
 'every week': 631,
 'week txt': 2371,
 'txt nokia': 2214,
 'nokia get': 1436,
 'get txting': 788,
 'txting tell': 2224,
 'tell ur': 2080,
 'ur mate': 2264,
 'mate www': 1269,
 'www getzed': 2456,
 'getzed co': 795,
 'uk pobox': 2232,
 'pobox wq': 1605,
 'wq norm': 2447,
 'norm tone': 1443,
 'better': 168,
 'bb': 149,
 'use': 2282,
 'sweet': 2049,
 'sleep': 1902,
 'rose': 1763,
 'may': 1276,
 'sleep well': 1903,
 'anymore': 69,
 'time coming': 2138,
 'spoke': 1963,
 'video': 2297,
 'ave': 119,
 'vary': 2295,
 'post': 1617,
 'bcm': 150,
 'ldn': 1131,
 'camera phone': 283,
 'phone call': 1555,
 'call call': 244,
 'cost ppm': 430,
 'call min': 255,
 'book': 194,
 'thk': 2122,
 'cine': 340,
 'mah': 1244,
 'need go': 1407,
 'price': 1635,
 'orange': 1503,
 'rental': 1723,
 'stoptxt': 2003,
 'mths half': 1377,
 'half price': 900,
 'price orange': 1637,
 'orange line': 1504,
 'line rental': 1170,
 'latest camera': 1121,
 'phone free': 1556,
 'plenty': 1585,
 'spent': 1959,
 'xxxx': 2469,
 'usf': 2285,
 'guess': 885,
 'private': 1639,
 'statement': 1979,
 'identifier': 1003,
 'expires': 648,
 'private account': 1640,
 'account statement': 8,
 'statement show': 1980,
 'call identifier': 250,
 'identifier code': 1004,
 'code expires': 365,
 'haha': 894,
 'heard': 921,
 'expect': 644,
 'get back': 780,
 'quiz': 1667,
 'flower': 709,
 'oh ok': 1470,
 'kano': 1069,
 'treat': 2185,
 'afternoon': 29,
 'boytoy': 209,
 'police': 1609,
 'miss': 1321,
 'good afternoon': 835,
 'listen': 1174,
 'somebody': 1925,
 'landline': 1103,
 'give call': 804,
 'call landline': 253,
 'ring': 1750,
 'hot': 977,
 'mobile number': 1341,
 'call back': 243,
 'face': 653,
 'themob': 2113,
 'hit': 946,
 'link': 1172,
 'crazy': 444,
 'created': 445,
 'gap': 765,
 'finger': 696,
 'made': 1242,
 'amp': 58,
 'fill': 685,
 'holding': 957,
 'god created': 823,
 'created gap': 446,
 'fill gap': 686,
 'gap holding': 766,
 'imagine': 1012,
 'urself': 2281,
 'hw': 997,
 'cell': 315,
 'thnk': 2123,
 'missed': 1324,
 'loving': 1224,
 'frnds': 751,
 'cant': 288,
 'live': 1177,
 'goodmorning': 845,
 'pas': 1531,
 'lead': 1133,
 'til': 2135,
 'midnight': 1302,
 'gonna get': 833,
 'online': 1490,
 'double': 552,
 'wif': 2395,
 'wun': 2453,
 'cut': 462,
 'short': 1864,
 'look': 1200,
 'ok lar': 1472,
 'tm': 2145,
 'smile': 1912,
 'last night': 1112,
 'going sleep': 830,
 'customer place': 460,
 'happens': 908,
 'insurance': 1031,
 'deliver': 505,
 'currently': 456,
 'friday': 742,
 'person': 1548,
 'guide': 886,
 'want come': 2331,
 'medical insurance': 1285,
 'freemsg': 739,
 'horny': 973,
 'ltd': 1230,
 'stop': 1992,
 'reply stop': 1729,
 'stop end': 1995,
 'house': 981,
 'usual': 2287,
 'iam': 998,
 'happy': 910,
 'fine happy': 695,
 'valued': 2294,
 'pleased': 1583,
 'review': 1745,
 'mob': 1333,
 'awarded bonus': 127,
 'prize call': 1642,
 'someone': 1926,
 'dating': 477,
 'revealed': 1744,
 'xy': 2470,
 'someone know': 1928,
 'dating service': 478,
 'call revealed': 262,
 'laptop': 1107,
 'izzit': 1047,
 'ur laptop': 2259,
 'straight': 2009,
 'winner': 2408,
 'specially': 1956,
 'speak': 1950,
 'operator': 1495,
 'winner specially': 2409,
 'specially selected': 1957,
 'receive cash': 1705,
 'cash award': 304,
 'speak live': 1951,
 'live operator': 1179,
 'operator claim': 1496,
 'pm cost': 1598,
 'pete': 1552,
 'college': 377,
 'jus': 1065,
 'ate': 109,
 'honey': 963,
 'ar': 86,
 ...}

In [48]:
#output features
y=pd.get_dummies(messages['label'], dtype=int)

In [49]:
y.head()

   ham  spam
0    1     0
1    1     0
2    0     1
3    1     0
4    1     0

In [50]:
y=y.iloc[:,0].values

In [51]:
#traintestsplit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [52]:
from sklearn.naive_bayes import MultinomialNB

In [53]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [54]:
y_pred=spam_detect_model.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score,classification_report

In [56]:
y.shape

(5572,)

In [57]:
accuracy_score(y_test,y_pred)

0.9856502242152466

In [58]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.95      0.95       151
           1       0.99      0.99      0.99       964

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

Using tfidf model for spam classification

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X1=tfidf.fit_transform(corpus).toarray()

In [60]:
#traintestsplit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.20)

In [61]:
spam_detect_model1=MultinomialNB().fit(X_train,y_train)
y_pred1=spam_detect_model1.predict(X_test)

In [62]:
accuracy_score(y_test,y_pred1)

0.9713004484304932

In [63]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.10      0.10      0.10       158
           1       0.85      0.86      0.85       957

    accuracy                           0.75      1115
   macro avg       0.48      0.48      0.48      1115
weighted avg       0.75      0.75      0.75      1115

correct sequence
1. preprocessing and cleaning
2. train test split
3. BOW and TF- IDF(prevent data leakage)
4. trained our model

In [64]:
y1=pd.get_dummies(messages['label'], dtype=int)
y1=y1.iloc[:,0].values

In [65]:
#traintestsplit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y1,test_size=0.20)

In [66]:
X_train[:10]

['end might still vomit okay everything come',
 'ok u take shopping u get paid',
 'december mobile mths entitled update latest colour camera mobile free call mobile update vco free',
 'free st week entry textpod chance win gb ipod cash every wk txt pod t c www textpod net custcare',
 'realy sorry recognise number confused r u please',
 'hi elaine today meeting confirmed',
 'tessy pls favor pls convey birthday wish nimya pls dnt forget today birthday shijas',
 'today voda number ending selected receive award match please call quoting claim code standard rate app',
 'dude teresa hope okay didnt hear people called received package since dec lt gt thot ld like know fantastic year best reading plus really really bam first aid usmle work done',
 'please da call mistake side sorry da pls da goto doctor']

In [67]:
len(X_train)

4457

In [68]:
#create BOW
from sklearn.feature_extraction.text import CountVectorizer
#for binary BOW enable binary=TRUE
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()
X_test= cv.transform(X_test).toarray()

In [69]:
X_train[:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [70]:
spam_detect_model1=MultinomialNB().fit(X_train,y_train)
y_pred1=spam_detect_model1.predict(X_test)

In [71]:
accuracy_score(y_test,y_pred1)

0.9820627802690582

In [72]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.16      0.15      0.15       163
           1       0.86      0.86      0.86       952

    accuracy                           0.76      1115
   macro avg       0.51      0.51      0.51      1115
weighted avg       0.75      0.76      0.76      1115